site_url: https://tee-travels.benward.io
search: false
backend:
  name: github
  branch: main
  repo: benw151/tee-travels
  base_url: https://oauth.tee-travels.benward.io

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{country}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "This will also be used for SEO page meta.",
        }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "This will also be used for SEO page meta.",
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Country",
          name: "country",
          widget: "relation",
          collection: "destination",
          search_fields: ["title"],
          value_field: "title",
          display_fields: ["title"],
          required: false,
          multiple: false,
        }
      - {
          label: "Region",
          name: "region",
          widget: "select",
          options: ["europe", "asia", "north-america", "oceania", "resources", "none"],
          required: false,
          multiple: false,
        }
      - {
          label: "Tag",
          name: "tag",
          widget: "string",
          hint: "Must exactly match related pages. Use all lower case and put dashes between words (Like this: tag-example)",
          pattern:
            [
              "^[a-z]+(-[a-z]+)*$",
              "Use all lower case and put dashes between words (Like this: tag-example)",
            ],
        }
      - {
          label: "Header Image URL",
          name: "headerImageUrl",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "Header Image Alt Text",
          name: "headerImageAlt",
          widget: "string",
        }
      - {
          label: "Section One Title",
          name: "sectionOneTitle",
          widget: "string",
          required: true,
        }
      - {
          label: "Section One Text",
          name: "sectionOneText",
          widget: "text",
          required: true,
        }
      - {
          label: "Section One Image URL",
          name: "sectionOneImageUrl",
          widget: "image",
          required: true,
        }
      - {
          label: "Section One Image Alt Text",
          name: "sectionOneImageAlt",
          widget: "string",
          required: true,
        }

      - {
          label: "Section Two Title",
          name: "sectionTwoTitle",
          widget: "string",
          required: true,
        }
      - {
          label: "Section Two Text",
          name: "sectionTwoText",
          widget: "text",
          required: true,
        }
      - {
          label: "Section Two Image URL",
          name: "sectionTwoImageUrl",
          widget: "image",
          required: true,
        }
      - {
          label: "Section Two Image Alt Text",
          name: "sectionTwoImageAlt",
          widget: "string",
          required: true,
        }

      - {
          label: "Section Three Title",
          name: "sectionThreeTitle",
          widget: "string",
          required: true,
        }
      - {
          label: "Section Three Text",
          name: "sectionThreeText",
          widget: "text",
          required: true,
        }
      - {
          label: "Section Three Image URL",
          name: "sectionThreeImageUrl",
          widget: "image",
          required: true,
        }
      - {
          label: "Section Three Image Alt Text",
          name: "sectionThreeImageAlt",
          widget: "string",
          required: true,
        }

      - {
          label: "Section Four Title",
          name: "sectionFourTitle",
          widget: "string",
          required: true,
        }
      - {
          label: "Section Four Text",
          name: "sectionFourText",
          widget: "text",
          required: true,
        }
      - {
          label: "Section Four Image URL",
          name: "sectionFourImageUrl",
          widget: "image",
          required: true,
        }
      - {
          label: "Section Four Image Alt Text",
          name: "sectionFourImageAlt",
          widget: "string",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "destination"
    label: "Destinations"
    folder: "content/destinations"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Country",
          name: "country",
          widget: "string",
          pattern: ["^[a-z]+$", "Must be lower case"],
        }
      - {
          label: "Header Image URL",
          name: "headerImageUrl",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "Header Image Alt Text",
          name: "headerImageAlt",
          widget: "string",
        }
      - {
          label: "Currency",
          name: "currency",
          widget: "string",
          hint: "Use international currency code, EUR, GBP, USD, etc.",
        }
      - { label: "Spending", name: "spending", widget: "string" }
      - {
          label: "spending Image URL",
          name: "spendingImageUrl",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "spending Image Alt Text",
          name: "spendingImageAlt",
          widget: "string",
        }
      - { label: "Getting Around", name: "gettingAround", widget: "string" }
      - {
          label: "gettingAround Image URL",
          name: "gettingAroundImageUrl",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "gettingAround Image Alt Text",
          name: "gettingAroundImageAlt",
          widget: "string",
        }
      - { label: "Things To Do", name: "thingsToDo", widget: "string" }
      - {
          label: "thingsToDo Image URL",
          name: "thingsToDoImageUrl",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "thingsToDo Image Alt Text",
          name: "thingsToDoImageAlt",
          widget: "string",
        }
      - { label: "Where To Stay", name: "whereToStay", widget: "string" }
      - {
          label: "whereToStay Image URL",
          name: "whereToStayImageUrl",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "whereToStay Image Alt Text",
          name: "whereToStayImageAlt",
          widget: "string",
        }
      - {
          label: "FAQ Worth Visiting",
          name: "faqWorthVisiting",
          widget: "string",
        }
      - { label: "FAQ Cheap", name: "faqCheap", widget: "string" }
      - { label: "FAQ Water", name: "faqWater", widget: "string" }
      - { label: "FAQ Visa", name: "faqVisa", widget: "string" }
      - { label: "FAQ Insurance", name: "faqInsurance", widget: "string" }
      - { label: "FAQ Safety", name: "faqSafety", widget: "string" }
