name: Auto Approve PRs

on:
  pull_request:
    branches: ["**"]  # This will trigger on PRs to any branch.
  pull_request_target:
    types: [opened, reopened, synchronize]  # For events targeting elevated permissions.
  workflow_dispatch:  # Allows manual triggering.

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Required to allow the bot to approve PRs.

    steps:
      # Log information for debugging
      - name: Log pull request details
        run: |
          echo "Triggered event: ${{ github.event_name }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR status: ${{ github.event.pull_request.state }}"

      - name: Auto-Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Log the result of the approval action
      - name: Log auto-approve result
        run: |
          echo "Auto-approve action finished for PR #${{ github.event.pull_request.number }}"
