name: Auto Approve PRs

on:
  pull_request_target:  # This ensures the action runs for pull requests targeting your repo
  workflow_dispatch:
  
jobs:
  auto_approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # This is necessary for approving the pull requests
    steps:
      - name: Auto-Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Uses the GitHub token to authenticate
