name: Auto Merge CMS PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Auto-merge CMS pull requests
        if: startsWith(github.head_ref, 'cms/') && github.event.pull_request.base.ref == 'staging'
        run: |
          git fetch origin pull/${{ github.event.number }}/head:pr_branch
          git checkout pr_branch
          git merge origin/staging --no-ff --no-edit
          git push origin pr_branch
